version: '3'
services:
  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "3000:3000"  # Expose backend port as 3000 externally
    depends_on:
      - mongo  # Backend depends on MongoDB

  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
    ports:
      - "8181:80"  # Expose frontend port as 8181 externally
    depends_on:
      - backend  # Ensure backend is up before frontend

  mongo:
    image: mongo:latest  # MongoDB container for your app
    volumes:
      - mongodb:/data/db  # Persist data
    ports:
      - "27017:27017"  # Expose MongoDB port

volumes:
  mongodb:  # Persist MongoDB data
